# Generated by Django 2.1.7 on 2019-06-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Core',
            new_name='ContactUs',
        ),
    ]
